# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5079a03496cc07a9dd173d0723cf1418d53b04390903898254e3802e56a10f2cc27f30b3b0824fc672fba6270247c0e71923e42bde3f811e0cca9c21674e98

test:
  secret_key_base: 74fa56062020b653176d16655d1886c782e86133acfb0d0ac5df6ae5ffc51950c785df38f19893f5a8b4fe95fa84a2af04af38320f7d628b525ad5d45d19db7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
